# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Campo')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Elemento')),
            ],
            options={
                'verbose_name': 'Elemento Campo',
                'verbose_name_plural': 'Elementos Campos',
            },
        ),
        migrations.CreateModel(
            name='ElementoCampoPredefinido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Elemento')),
            ],
            options={
                'verbose_name': 'Elemento Campo Predefinido',
                'verbose_name_plural': 'Elemento Campos Predefinidos',
            },
        ),
    ]
