# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-25 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ioteca_service_apps.rleg.models.ElementoCampoRegistro


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat', '0001_initial'),
        ('cleg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Campo')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Elemento')),
            ],
            options={
                'verbose_name': 'Elemento Campo',
                'verbose_name_plural': 'Elementos Campos',
            },
        ),
        migrations.CreateModel(
            name='ElementoCampoPredefinido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Elemento')),
            ],
            options={
                'verbose_name': 'Elemento Campo Predefinido',
                'verbose_name_plural': 'Elemento Campos Predefinidos',
            },
        ),
        migrations.CreateModel(
            name='ElementoCampoPredefinidoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('elemento_campo_pred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rleg.ElementoCampoPredefinido')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.Persona')),
            ],
            options={
                'verbose_name': 'Elemento Campo Predefinido Registro',
                'verbose_name_plural': 'Elemento Campo Predefinido de Registros',
            },
        ),
        migrations.CreateModel(
            name='ElementoCampoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_string', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dato String')),
                ('d_select', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dato Select')),
                ('d_opcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dato Select Opción')),
                ('d_texto', models.TextField(blank=True, null=True, verbose_name='Dato Descripción')),
                ('d_number', models.IntegerField(blank=True, null=True, verbose_name='Dato Número')),
                ('d_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dato Decimal')),
                ('d_fecha', models.IntegerField(blank=True, null=True, verbose_name='Dato Fecha')),
                ('d_imagen', models.ImageField(blank=True, null=True, upload_to=ioteca_service_apps.rleg.models.ElementoCampoRegistro.upload_image, verbose_name='Dato Imagen')),
                ('d_archivo', models.FileField(blank=True, null=True, upload_to=ioteca_service_apps.rleg.models.ElementoCampoRegistro.upload_file, verbose_name='Dato Archivo')),
                ('d_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Dato URL')),
                ('elemento_campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rleg.ElementoCampo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elementocamporegistro', to='cat.Persona')),
            ],
            options={
                'verbose_name': 'Elemento Campo Registro',
                'verbose_name_plural': 'Elemento Campo de Registros',
            },
        ),
    ]
