# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_auto_20161007_0118'),
        ('rleg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoCampoPredefinidoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('elemento_campo_pred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rleg.ElementoCampoPredefinido')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.Persona')),
            ],
            options={
                'verbose_name_plural': 'Elemento Campo Predefinido de Registros',
                'verbose_name': 'Elemento Campo Predefinido Registro',
            },
        ),
        migrations.CreateModel(
            name='ElementoCampoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('elemento_campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rleg.ElementoCampo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elementocamporegistro', to='cat.Persona')),
            ],
            options={
                'verbose_name_plural': 'Elemento campo de Registros',
                'verbose_name': 'Elemento Campo Registro',
            },
        ),
    ]
