# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-22 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import ioteca_service_apps.rleg.models.ElementoCampoRegistro


class Migration(migrations.Migration):

    dependencies = [
        ('rleg', '0002_elementocampopredefinidoregistro_elementocamporegistro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementocamporegistro',
            options={'verbose_name': 'Elemento Campo Registro', 'verbose_name_plural': 'Elemento Campo de Registros'},
        ),
        migrations.RemoveField(
            model_name='elementocamporegistro',
            name='data',
        ),
        migrations.AddField(
            model_name='elementocamporegistro',
            name='d_archivo',
            field=models.FileField(blank=True, null=True, upload_to=ioteca_service_apps.rleg.models.ElementoCampoRegistro.upload_file, verbose_name=b'Dato Archivo'),
        ),
        migrations.AddField(
            model_name='elementocamporegistro',
            name='d_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name=b'Dato Decimal'),
        ),
        migrations.AddField(
            model_name='elementocamporegistro',
            name='d_fecha',
            field=models.DateField(blank=True, null=True, verbose_name=b'Dato Fecha'),
        ),
        migrations.AddField(
            model_name='elementocamporegistro',
            name='d_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=ioteca_service_apps.rleg.models.ElementoCampoRegistro.upload_image, verbose_name=b'Dato Imagen'),
        ),
        migrations.AddField(
            model_name='elementocamporegistro',
            name='d_number',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Dato N\xc3\xbamero'),
        ),
        migrations.AddField(
            model_name='elementocamporegistro',
            name='d_string',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Dato String'),
        ),
        migrations.AddField(
            model_name='elementocamporegistro',
            name='d_texto',
            field=models.TextField(blank=True, null=True, verbose_name=b'Dato Descripci\xc3\xb3n'),
        ),
        migrations.AddField(
            model_name='elementocamporegistro',
            name='d_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name=b'Dato URL'),
        ),
    ]
