# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import ioteca_service_apps.rleg.models.ElementoCampoRegistro


class Migration(migrations.Migration):

    dependencies = [
        ('rleg', '0003_auto_20161122_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementocamporegistro',
            name='d_archivo',
            field=models.FileField(blank=True, null=True, upload_to=ioteca_service_apps.rleg.models.ElementoCampoRegistro.upload_file, verbose_name='Dato Archivo'),
        ),
        migrations.AlterField(
            model_name='elementocamporegistro',
            name='d_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dato Decimal'),
        ),
        migrations.AlterField(
            model_name='elementocamporegistro',
            name='d_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Dato Fecha'),
        ),
        migrations.AlterField(
            model_name='elementocamporegistro',
            name='d_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=ioteca_service_apps.rleg.models.ElementoCampoRegistro.upload_image, verbose_name='Dato Imagen'),
        ),
        migrations.AlterField(
            model_name='elementocamporegistro',
            name='d_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dato Número'),
        ),
        migrations.AlterField(
            model_name='elementocamporegistro',
            name='d_string',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dato String'),
        ),
        migrations.AlterField(
            model_name='elementocamporegistro',
            name='d_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Dato Descripción'),
        ),
        migrations.AlterField(
            model_name='elementocamporegistro',
            name='d_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Dato URL'),
        ),
    ]
