# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-21 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Campos',
                'verbose_name': 'Campo',
            },
        ),
        migrations.CreateModel(
            name='CampoPredefinido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Campos Prefefinidos',
                'verbose_name': 'Campo Prefefinido',
            },
        ),
        migrations.CreateModel(
            name='CampoPropiedadForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Campos Propiedades Forms',
                'verbose_name': 'Campo Propiedad Form',
            },
        ),
        migrations.CreateModel(
            name='CargoOcupado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cargos Ocupados',
                'verbose_name': 'Cargo Ocupado',
            },
        ),
        migrations.CreateModel(
            name='CategoriaAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Catergorias Academicas',
                'verbose_name': 'Catergoria Academica',
            },
        ),
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Codigos Postales',
                'verbose_name': 'Codigo Postal',
            },
        ),
        migrations.CreateModel(
            name='DataCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Data Campos',
                'verbose_name': 'Data Campo',
            },
        ),
        migrations.CreateModel(
            name='DataCampoOpcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('data_campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.DataCampo')),
            ],
            options={
                'verbose_name_plural': 'Data Campos Opciones',
                'verbose_name': 'Data Campo Opción',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'verbose_name': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Dimensiones',
                'verbose_name': 'Dimension',
            },
        ),
        migrations.CreateModel(
            name='DimensionNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Dimension')),
            ],
            options={
                'verbose_name_plural': 'Dimensiones Niveles',
                'verbose_name': 'Dimension Nivel',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Distritos',
                'verbose_name': 'Distrito',
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cgen.Item')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cgen.Seccion')),
                ('sub_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cgen.SubItem')),
            ],
            options={
                'verbose_name_plural': 'Elementos',
                'verbose_name': 'Elemento',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'verbose_name': 'Especialidad',
            },
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name_plural': 'Grados Academicos',
                'verbose_name': 'Grado Academico',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name_plural': 'Idiomas',
                'verbose_name': 'Idioma',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name_plural': 'Instituciones',
                'verbose_name': 'Institucion',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Niveles',
                'verbose_name': 'Nivel',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', django_countries.fields.CountryField(max_length=2)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'verbose_name': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='ProcesoGradoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name_plural': 'Procesos de Grados Academicos',
                'verbose_name': 'Proceso de Grado Academico',
            },
        ),
        migrations.CreateModel(
            name='PropiedadForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Propiedad Forms',
                'verbose_name': 'Propiedad Form',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Departamento')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'verbose_name': 'Provincia',
            },
        ),
        migrations.CreateModel(
            name='RegimenPension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name_plural': 'Régimen de Pensiones',
                'verbose_name': 'Régimen Pension',
            },
        ),
        migrations.CreateModel(
            name='TipoCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Campos',
                'verbose_name': 'Tipo Campo',
            },
        ),
        migrations.CreateModel(
            name='TipoInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo Instituciones',
                'verbose_name': 'Tipo Institucion',
            },
        ),
        migrations.CreateModel(
            name='TipoNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos Niveles',
                'verbose_name': 'Tipo Nivel',
            },
        ),
        migrations.AddField(
            model_name='propiedadform',
            name='tipo_campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.TipoCampo'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='tipo_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.TipoNivel'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='tipo_isntitucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.TipoInstitucion'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Provincia'),
        ),
        migrations.AddField(
            model_name='dimensionnivel',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Nivel'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Idioma'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Pais'),
        ),
    ]
