# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='CampoPredefinido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campo Prefefinido',
                'verbose_name_plural': 'Campos Prefefinidos',
            },
        ),
        migrations.CreateModel(
            name='CampoPropiedadForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Campo Propiedad Form',
                'verbose_name_plural': 'Campos Propiedades Forms',
            },
        ),
        migrations.CreateModel(
            name='CargoOcupado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo Ocupado',
                'verbose_name_plural': 'Cargos Ocupados',
            },
        ),
        migrations.CreateModel(
            name='CategoriaAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catergoria Academica',
                'verbose_name_plural': 'Catergorias Academicas',
            },
        ),
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Codigo Postal',
                'verbose_name_plural': 'Codigos Postales',
            },
        ),
        migrations.CreateModel(
            name='DataCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Data Campo',
                'verbose_name_plural': 'Data Campos',
            },
        ),
        migrations.CreateModel(
            name='DataPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('data_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPropiedadForm')),
            ],
            options={
                'verbose_name': 'Data Propiedad',
                'verbose_name_plural': 'Data Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dimension',
                'verbose_name_plural': 'Dimensiones',
            },
        ),
        migrations.CreateModel(
            name='DimensionNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Dimension')),
            ],
            options={
                'verbose_name': 'Dimension Nivel',
                'verbose_name_plural': 'Dimensiones Niveles',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cgen.Item')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cgen.Seccion')),
                ('sub_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cgen.SubItem')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name': 'Grado Academico',
                'verbose_name_plural': 'Grados Academicos',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='ProcesoGradoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('campo_predefinido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.CampoPredefinido')),
            ],
            options={
                'verbose_name': 'Proceso de Grado Academico',
                'verbose_name_plural': 'Procesos de Grados Academicos',
            },
        ),
        migrations.CreateModel(
            name='PropiedadForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Propiedad Form',
                'verbose_name_plural': 'Propiedad Forms',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Departamento')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='TipoCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo Campo',
                'verbose_name_plural': 'Tipo de Campos',
            },
        ),
        migrations.CreateModel(
            name='TipoInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Institucion',
                'verbose_name_plural': 'Tipo Instituciones',
            },
        ),
        migrations.CreateModel(
            name='TipoNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Nivel',
                'verbose_name_plural': 'Tipos Niveles',
            },
        ),
        migrations.AddField(
            model_name='propiedadform',
            name='tipo_campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.TipoCampo'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='tipo_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.TipoNivel'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='tipo_isntitucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.TipoInstitucion'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Provincia'),
        ),
        migrations.AddField(
            model_name='dimensionnivel',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Nivel'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Idioma'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleg.Pais'),
        ),
    ]
